name: Run API Tests  # Name of the workflow

on:  # Defines the events that will trigger this workflow
  push:  # Trigger the workflow when code is pushed to the repository
    branches:  # Specify branches to watch for code changes
      - main
  pull_request:  # Trigger the workflow when a pull request is created or updated
    branches:
      - main

jobs:  # Defines the jobs to run as part of this workflow
  run-tests:  # Name of the job
    runs-on: ubuntu-latest  # Use Ubuntu as the runner (Linux environment)

    steps:  # Each step in the job
    - name: Checkout code  # Step 1: Check out the code from your GitHub repository.
      uses: actions/checkout@v3  # Action to clone the repo

    - name: Set up Python  # Step 2: Set up Python environment on the runner
      uses: actions/setup-python@v4  # Official GitHub Action to set up a specific Python version
      with:
        python-version: 3.12 # Use Python 3.12.x version

    - name: Install dependencies  # Step 3: Install the required Python packages
      run: |  
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate virtual environment (Linux/macOS syntax)
          pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies

    - name: Run tests  # Step 4: Execute the API tests.
      run: |  
          source venv/bin/activate  # Ensure the virtual environment is activated
          pytest -v  # Run tests with verbose output

